### ISSUE TITLE
Should say observeEventType:andPreviousSiblingKeyWithBlock: 

### ISSUE THREAD

**Issue by hsavit1** [joenoon/Firebase-RACExtensions#1]
Please up date the FQuery class with the updated version of Firebase

**Comment by joenoon** [comment]
Hi @hsavit1, can you please submit a PR?  I'm no longer using this pod.

**Comment by hsavit1** [comment]
For sure

**Comment by hsavit1** [comment]
this was my mistake! your doc is still relevant :+1:
